name: rirev_flutter_toolkit
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Copy to clipboard
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
