name: rirev_flutter_toolkit
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Copy to clipboard
  clipboard: ^0.1.2+8

  # Upload files
  dio: ^3.0.10

  # Launch urls
  url_launcher: ^5.5.0

  # Open pdfs
  open_file: ^3.0.1

  # Manage location, storage, and contacts permissions
  permission_handler: ^5.0.1+1

  # internationalization and localization facilities
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
